/* eslint-disable no-shadow */
export enum PROFESSIONAL_TYPES {
  AGENT_BROKER = 1,
  LENDER,
  HOME_IMPROVE_SERVICES,
  LANDLORD,
  PHOTOGRAPHER,
  HOME_BUILDER,
  HOME_INSPECTOR,
  PROPERTY_MANAGER,
  OTHER_PROFESSIONAL,
}
